//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeYonetim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjeYonetimEntities : DbContext
    {
        public ProjeYonetimEntities()
            : base("name=ProjeYonetimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<ProjeDurumlari> ProjeDurumlari { get; set; }
        public virtual DbSet<Projeler> Projeler { get; set; }
        public virtual DbSet<VW_Projeler> VW_Projeler { get; set; }
    }
}
