//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeYonetim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Projeler
    {
        public int PROJE_ID { get; set; }
        public Nullable<int> DURUM_ID { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public int KULLANICI_ID { get; set; }
        public string ProjeAdi { get; set; }
        public string DurumAdi { get; set; }
        public string KullaniciAdi { get; set; }
    }
}
